<?php
/**
 * tools/obfuscate_secrets.php
 * Run once: php tools/obfuscate_secrets.php
 * Generates obfuscated PHP code for the two secrets.
 * DELETE after use.
 */

// ── PUT YOUR REAL SECRETS HERE ────────────────────────────────────────────────
$hmacSecret = 'a3f7c1e9b52d804f6b9a3e71d4c28f570a6b1e3d9c52f804a7b1e3c9d52f8044';
$aesSalt    = '9e82c17a4f3b5d60e4a92c17a8f3b5d60e4a92c17a8f3b5d60e4a92c17a8f3b';

// XOR function
function xorStr(string $data, string $key): string {
    $out = '';
    $kl = strlen($key);
    for ($i = 0, $l = strlen($data); $i < $l; $i++) {
        $out .= chr(ord($data[$i]) ^ ord($key[$i % $kl]));
    }
    return $out;
}

// Split a string into N chunks of random sizes (min 8, max 20 chars)
function splitRandom(string $s): array {
    $chunks = [];
    $len = strlen($s);
    $pos = 0;
    while ($pos < $len) {
        $take = min(random_int(8, 16), $len - $pos);
        $chunks[] = substr($s, $pos, $take);
        $pos += $take;
    }
    return $chunks;
}

// Generate a random XOR key of given length
function randKey(int $len): string {
    $k = '';
    for ($i = 0; $i < $len; $i++) {
        // printable non-quote chars
        $k .= chr(random_int(35, 90));
    }
    return $k;
}

function buildObfuscated(string $secret, string $varName): string {
    $chunks   = splitRandom($secret);
    $numChunks = count($chunks);
    $lines    = [];
    $assembleVars = [];

    foreach ($chunks as $i => $chunk) {
        $key      = randKey(strlen($chunk));
        $xored    = xorStr($chunk, $key);
        $b64data  = base64_encode($xored);
        $b64key   = base64_encode($key);
        $varData  = "\$_d{$varName}{$i}";
        $varKey   = "\$_k{$varName}{$i}";
        $varChunk = "\$_c{$varName}{$i}";

        $lines[] = "{$varData}=base64_decode('{$b64data}');";
        $lines[] = "{$varKey}=base64_decode('{$b64key}');";
        $lines[] = "{$varChunk}=implode('',array_map('chr',array_map(fn(\$a,\$b)=>\$a^\$b,array_map('ord',str_split({$varData})),array_map('ord',str_split({$varKey})))));";

        $assembleVars[] = $varChunk;
    }

    // Shuffle line order slightly for visual confusion (but keep logic correct)
    $assemble = implode('.', $assembleVars);
    $lines[]  = "define('{$varName}',{$assemble});";

    // Add some decoy variable to confuse static analysis
    $decoyVal = base64_encode(random_bytes(12));
    $lines[]  = "\$_x{$varName}=null;unset(\$_x{$varName}); // {$decoyVal}";

    return implode("\n", $lines);
}

// Shuffle the chunk vars inside: interleave HMAC and AES lines for extra confusion
$hmacCode = buildObfuscated($hmacSecret, '_SM_HMAC_SECRET');
$aesCode  = buildObfuscated($aesSalt,    '_SM_AES_SALT');

// Interleave lines
$hmacLines = explode("\n", $hmacCode);
$aesLines  = explode("\n", $aesCode);

$merged = [];
$hi = 0; $ai = 0;
$ht = count($hmacLines); $at = count($aesLines);
while ($hi < $ht || $ai < $at) {
    if ($hi < $ht) $merged[] = $hmacLines[$hi++];
    if ($ai < $at) $merged[] = $aesLines[$ai++];
}
$final = implode("\n", $merged);

echo "<?php\n";
echo "// ═══ OBFUSCATED SECRETS — generated by obfuscate_secrets.php ═══\n";
echo "// Do NOT edit these lines manually.\n";
echo $final . "\n";
echo "// ═══════════════════════════════════════════════════════════════\n";
